theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: VINN
name: The Surprising Effectiveness of Representation Learning for Visual Imitation
# Short bio or description (displayed in the header)
description: 
